### ISSUE TITLE
fix parenthesis in rendering

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/HZ#20]
this is after a bunch of construct aps then a bunch of construct plusses
<img width="486" alt="screen shot 2016-10-08 at 12 14 46 pm" src="https://cloud.githubusercontent.com/assets/4099104/19214455/91c4825a-8d52-11e6-9343-289b48569fbe.png">

**Comment by ivoysey** [comment]
this may or may not help, but some (maybe all?) of the parens that were missing started to render as i moved the cursor around.
<img width="1092" alt="screen shot 2016-10-08 at 5 12 20 pm" src="https://cloud.githubusercontent.com/assets/4099104/19215960/7afcf7be-8d7a-11e6-8eb3-88d7d9669ea4.png">

**Comment by MichaelHilton** [comment]
So much better!! :-P
![image](https://cloud.githubusercontent.com/assets/1170420/19216358/06e03268-8d6d-11e6-9b02-69aefc3baace.png)
