### ISSUE TITLE
make any number key activate construct lit

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/HZ#22]
intended behavior: press any number key -> focus moves to the construct lit box with that number entered into it

**Comment by MichaelHilton** [comment]
@cyrus- then we need to find new hotkeys for move child. Suggestions?

**Comment by cyrus-** [comment]
oh yeah, didn't notice that. OK, I guess it's fine for now. Maybe change the construct lit hotkey from t to #?

**Comment by MichaelHilton** [comment]
sure, that's not a problem.

**Comment by MichaelHilton** [comment]
Fixed by changing lit hotkey from t to #
