### ISSUE TITLE
workflow for making lambdas and numeric literals

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/HZ#28]
it's a little weird to create a lam. cause the action's greyed out even when it's ok until you supply the variable. so it kind of looks like it's not ok. and then you put a variable in the text box, and press the action key but that changes the variable name from `x` to `x\`. the hot key only works again after you click outside the box to remove focus

**Comment by cyrus-** [comment]
the intent is for \ to move you to the box to enter the variable name, and then enter does the action. so roughly following what you would do in e.g. Haskell -- type '\' then the variable then '.' or whatever

**Comment by ivoysey** [comment]
ah! that is smoother; I hadn't tripped across that particular pattern yet.

---Ian

**Comment by MichaelHilton** [comment]
We could put in a "placeholder" string to try to make it easier for users.  What do you think?
There is probably a better string than "enter a value"
<img width="379" alt="screen shot 2016-10-10 at 9 24 00 am" src="https://cloud.githubusercontent.com/assets/1170420/19243167/53556140-8ecb-11e6-9861-e482f2499f34.png">

**Comment by cyrus-** [comment]
"(enter variable then press ENTER)" perhaps?

Also it might clarify matters + make it more consistent with the paper for
the input boxes to be to the right of the buttons.

**Comment by MichaelHilton** [comment]
I'll try that out and post a screen shot...

**Comment by MichaelHilton** [comment]
Better?
<img width="497" alt="screen shot 2016-10-10 at 9 31 03 am" src="https://cloud.githubusercontent.com/assets/1170420/19243404/690e6c4c-8ecc-11e6-9153-ca66360072a3.png">

**Comment by cyrus-** [comment]
Should say variable not value. And the case button is still on the right.

**Comment by MichaelHilton** [comment]
are you ok with "var"? it is getting kinda long

**Comment by cyrus-** [comment]
Sure that's fine.

**Comment by MichaelHilton** [comment]
<img width="498" alt="screen shot 2016-10-10 at 9 36 55 am" src="https://cloud.githubusercontent.com/assets/1170420/19243663/55242f22-8ecd-11e6-8020-12ca83947f1a.png">

**Comment by cyrus-** [comment]
The construct lit one shouldn't say "var", that one is a "number". Other than that, looks good to me.

**Comment by ivoysey** [comment]
Looks good to me, too!

---Ian

**Comment by MichaelHilton** [comment]
I'm trying to come up with a way to have the button say "ap" like in the paper, but also say "application" so it is not too cryptic.  Not sold on this.... What do you think?

<img width="487" alt="screen shot 2016-10-10 at 9 40 57 am" src="https://cloud.githubusercontent.com/assets/1170420/19243736/b7408b42-8ecd-11e6-8091-3e4a79cd4491.png">

**Comment by cyrus-** [comment]
nah I don't think that's necessary. If someone isn't sure what a button does, playing with it a bit should clarify that. I like leaving the buttons with the same text as the actions in the paper.

**Comment by cyrus-** [comment]
If you really want to add some explanation, maybe add a tooltip?

**Comment by ivoysey** [comment]
maybe italics for the part that's the syntax from the shapes, and then the
full word for human readability? the caps jumps out a bit too much.

also, maybe `[ . ]` instead of `( . )` to show the hotkey on the buttons? i
just realized that's what that was for; i'd been confused by `(()` on the
ap button for a while but ignoring it.

---Ian

**Comment by cyrus-** [comment]
agreed on using [ . ] instead of ( . )

**Comment by MichaelHilton** [comment]
sounds good

**Comment by cyrus-** [comment]
or use some other styling for the hotkey, e.g. bold or a different background box. I think buttons can have arbitrary HTML inside them

**Comment by MichaelHilton** [comment]
unfortunately, you can't style button labels with html...
<img width="982" alt="screen shot 2016-10-10 at 9 51 29 am" src="https://cloud.githubusercontent.com/assets/1170420/19244004/280b6044-8ecf-11e6-9631-21db10dd4142.png">

**Comment by MichaelHilton** [comment]
I'm thinking of making the "hazelnut" text here a link to the paper.  does that sound good? where should we link it to? 
<img width="334" alt="screen shot 2016-10-10 at 9 54 02 am" src="https://cloud.githubusercontent.com/assets/1170420/19244068/7e69054a-8ecf-11e6-9601-9c002dcda010.png">

**Comment by cyrus-** [comment]
That looks good to me.

Link to ArXiV for now. We should update ArXiV with the version of the paper we submitted to AE. I'll make an issue for that.

**Comment by ivoysey** [comment]
possibly just hazelgrove.org when it's live? that should have links to the
preprint and agda that are prominent.

---Ian

**Comment by cyrus-** [comment]
Yeah maybe label the link at the bottom "Source (OCaml): " and add another "Mechanization (Agda): " link below that

**Comment by MichaelHilton** [comment]
<img width="902" alt="screen shot 2016-10-10 at 10 06 06 am" src="https://cloud.githubusercontent.com/assets/1170420/19244446/331a23b0-8ed1-11e6-83ff-a56f55da251a.png">
