### ISSUE TITLE
Cannot construct lit.

### ISSUE THREAD

**Issue by joelburget** [hazelgrove/HZ#36]
I first construct `[] : num`. I expect to be able to enter a lit but that field is disabled. I try also constructing a plus, making state `[] + [] : num` but I still can't enter a lit.

I'd need to check the paper to see if I'm missing something but this is at least a bug in usability if not in implementation.

**Comment by cyrus-** [comment]
The UI there is definitely a little confusing -- the button doesn't light up until a valid literal is entered into the box, indicating that there is now a well-formed action that you can perform. You can still press "#" to bring focus to the box.

**Comment by cyrus-** [comment]
I'll look at adding some clarifying text at least. I think @asolove had some thoughts on making it a 3-mode button in some way.

**Comment by cyrus-** [comment]
I added a little clarifying comment to HZ.
